### PR TITLE
Some DB help. :^)

### PR DESCRIPTION
**Pull request by Kyousei**

### CODE REVIEW

**Comment by Kyousei** [comment]
You bastards, merge this xd.

**Comment by MrYetiGuy** [comment]
Thanks :D

**Comment by Kyousei** [comment]
You're whale cum.

**Comment by MrYetiGuy** [comment]
?

**Comment by MrYetiGuy** [comment]
Example

**Comment by Kyousei** [comment]
?

**Comment by Kyousei** [comment]
"You're whale cum" = "You're welcome."
Logic 101

**Pull request merged**
